<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CityTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $cities = array(
            array('id' => '1','slug' => 'baki','name' => 'BAKI','visible' => 1,'deliver_price' => 0),
            array('id' => '2','slug' => 'xirdalan','name' => 'XIRDALAN','visible' => 1,'deliver_price' => 1),
            array('id' => '3','slug' => 'sumqayit','name' => 'SUMQAYIT','visible' => 1,'deliver_price' => 3),
            array('id' => '4','slug' => 'agcabedi','name' => 'AĞCABƏDİ','visible' => 1,'deliver_price' => 0),
            array('id' => '5','slug' => 'agdam','name' => 'AĞDAM','visible' => 1,'deliver_price' => 0),
            array('id' => '6','slug' => 'agdas','name' => 'AĞDAŞ','visible' => 1,'deliver_price' => 0),
            array('id' => '7','slug' => 'agstafa','name' => 'AĞSTAFA','visible' => 1,'deliver_price' => 0),
            array('id' => '8','slug' => 'agsu','name' => 'AĞSU','visible' => 1,'deliver_price' => 0),
            array('id' => '9','slug' => 'astara','name' => 'ASTARA','visible' => 1,'deliver_price' => 2),
            array('id' => '10','slug' => 'balaken','name' => 'BALAKƏN','visible' => 1,'deliver_price' => 0),
            array('id' => '11','slug' => 'beyleqan','name' => 'BEYLƏQAN','visible' => 1,'deliver_price' => 4),
            array('id' => '12','slug' => 'berde','name' => 'BƏRDƏ','visible' => 1,'deliver_price' => 0),
            array('id' => '13','slug' => 'bilesuvar','name' => 'BİLƏSUVAR','visible' => 1,'deliver_price' => 8),
            array('id' => '14','slug' => 'celilabad','name' => 'CƏLİLABAD','visible' => 1,'deliver_price' => 0),
            array('id' => '15','slug' => 'daskesen','name' => 'DAŞKƏSƏN','visible' => 1,'deliver_price' => 0),
            array('id' => '16','slug' => 'fizuli','name' => 'FİZULİ','visible' => 1,'deliver_price' => 0),
            array('id' => '17','slug' => 'gedebey','name' => 'GƏDƏBƏY','visible' => 1,'deliver_price' => 0),
            array('id' => '18','slug' => 'gence','name' => 'GƏNCƏ','visible' => 1,'deliver_price' => 0),
            array('id' => '19','slug' => 'goranboy','name' => 'GORANBOY','visible' => 1,'deliver_price' => 0),
            array('id' => '20','slug' => 'goycay','name' => 'GÖYÇAY','visible' => 1,'deliver_price' => 0),
            array('id' => '21','slug' => 'goygol','name' => 'GÖYGÖL','visible' => 1,'deliver_price' => 0),
            array('id' => '22','slug' => 'goytepe','name' => 'GÖYTƏPƏ','visible' => 1,'deliver_price' => 0),
            array('id' => '23','slug' => 'haciqabul','name' => 'HACIQABUL','visible' => 1,'deliver_price' => 0),
            array('id' => '24','slug' => 'imisli','name' => 'İMİŞLİ','visible' => 1,'deliver_price' => 0),
            array('id' => '25','slug' => 'ismayilli','name' => 'İSMAYILLI','visible' => 1,'deliver_price' => 0),
            array('id' => '26','slug' => 'kurdemir','name' => 'KÜRDƏMİR','visible' => 1,'deliver_price' => 0),
            array('id' => '27','slug' => 'lerik','name' => 'LERİK','visible' => 1,'deliver_price' => 0),
            array('id' => '28','slug' => 'lenkeran','name' => 'LƏNKƏRAN','visible' => 1,'deliver_price' => 0),
            array('id' => '29','slug' => 'masalli','name' => 'MASALLI','visible' => 1,'deliver_price' => 0),
            array('id' => '30','slug' => 'mingecevir','name' => 'MİNGƏÇEVİR','visible' => 1,'deliver_price' => 0),
            array('id' => '31','slug' => 'naxcivan','name' => 'NAXÇIVAN','visible' => 1,'deliver_price' => 0),
            array('id' => '32','slug' => 'naftalan','name' => 'NAFTALAN','visible' => 1,'deliver_price' => 0),
            array('id' => '33','slug' => 'neftcala','name' => 'NEFTÇALA','visible' => 1,'deliver_price' => 0),
            array('id' => '34','slug' => 'oguz','name' => 'OĞUZ','visible' => 1,'deliver_price' => 0),
            array('id' => '35','slug' => 'qax','name' => 'QAX','visible' => 1,'deliver_price' => 0),
            array('id' => '36','slug' => 'qazax','name' => 'QAZAX','visible' => 1,'deliver_price' => 0),
            array('id' => '37','slug' => 'qebele','name' => 'QƏBƏLƏ','visible' => 1,'deliver_price' => 0),
            array('id' => '38','slug' => 'quba','name' => 'QUBA','visible' => 1,'deliver_price' => 0),
            array('id' => '39','slug' => 'qusar','name' => 'QUSAR','visible' => 1,'deliver_price' => 0),
            array('id' => '40','slug' => 'saatli','name' => 'SAATLI','visible' => 1,'deliver_price' => 0),
            array('id' => '41','slug' => 'sabirabad','name' => 'SABİRABAD','visible' => 1,'deliver_price' => 0),
            array('id' => '42','slug' => 'sabran','name' => 'ŞABRAN','visible' => 1,'deliver_price' => 0),
            array('id' => '43','slug' => 'salyan','name' => 'SALYAN','visible' => 1,'deliver_price' => 0),
            array('id' => '44','slug' => 'samaxi','name' => 'ŞAMAXI','visible' => 1,'deliver_price' => 0),
            array('id' => '45','slug' => 'seki','name' => 'ŞƏKİ','visible' => 1,'deliver_price' => 0),
            array('id' => '46','slug' => 'semkir','name' => 'ŞƏMKİR','visible' => 1,'deliver_price' => 0),
            array('id' => '47','slug' => 'sirvan','name' => 'ŞİRVAN','visible' => 1,'deliver_price' => 0),
            array('id' => '48','slug' => 'siyezen','name' => 'SİYƏZƏN','visible' => 1,'deliver_price' => 0),
            array('id' => '49','slug' => 'terter','name' => 'TƏRTƏR','visible' => 1,'deliver_price' => 0),
            array('id' => '50','slug' => 'tovuz','name' => 'TOVUZ','visible' => 1,'deliver_price' => 0),
            array('id' => '51','slug' => 'ucar','name' => 'UCAR','visible' => 1,'deliver_price' => 0),
            array('id' => '52','slug' => 'xacmaz','name' => 'XAÇMAZ','visible' => 1,'deliver_price' => 0),
            array('id' => '53','slug' => 'xirdalan','name' => 'XIRDALAN','visible' => 1,'deliver_price' => 0),
            array('id' => '54','slug' => 'xizi','name' => 'XIZI','visible' => 1,'deliver_price' => 0),
            array('id' => '55','slug' => 'xudat','name' => 'XUDAT','visible' => 1,'deliver_price' => 0),
            array('id' => '56','slug' => 'yevlax','name' => 'YEVLAX','visible' => 1,'deliver_price' => 0),
            array('id' => '57','slug' => 'zaqatala','name' => 'ZAQATALA','visible' => 1,'deliver_price' => 0),
            array('id' => '58','slug' => 'zerdab','name' => 'ZƏRDAB','visible' => 1,'deliver_price' => 0)
        );
        $regions = array(
            array('parent_id' => '1','name' => 'XƏTAİ','slug' => 'xetai'),
            array('parent_id' => '1','name' => 'ABŞERON','slug' => 'abseron'),
            array('parent_id' => '1','name' => 'BİNƏQƏDİ','slug' => 'bineqedi'),
            array('parent_id' => '1','name' => 'NƏRİMANOV','slug' => 'nerimanov'),
            array('parent_id' => '1','name' => 'NƏSİMİ','slug' => 'nesimi'),
            array('parent_id' => '1','name' => 'NİZAMİ','slug' => 'nizami'),
            array('parent_id' => '1','name' => 'PİRALLAHI','slug' => 'pirallahi'),
            array('parent_id' => '1','name' => 'QARADAĞ','slug' => 'qaradag'),
            array('parent_id' => '1','name' => 'SABUNÇU','slug' => 'sabuncu'),
            array('parent_id' => '1','name' => 'SƏBAİL','slug' => 'sebail'),
            array('parent_id' => '1','name' => 'SURAXANI','slug' => 'suraxani'),
            array('parent_id' => '1','name' => 'XƏZƏR','slug' => 'xezer'),
            array('parent_id' => '1','name' => 'YASAMAL','slug' => 'yasamal'),
            array('parent_id' => '3','name' => '1-ci MİKRORAYON','slug' => '1-ci-mikrorayon'),
            array('parent_id' => '3','name' => '2-ci MİKRORAYON','slug' => '2-ci-mikrorayon'),
            array('parent_id' => '3','name' => '3-ci MİKRORAYON','slug' => '3-ci-mikrorayon'),
            array('parent_id' => '3','name' => '4-ci MİKRORAYON','slug' => '4-ci-mikrorayon'),
            array('parent_id' => '3','name' => '5-ci MİKRORAYON','slug' => '5-ci-mikrorayon'),
            array('parent_id' => '3','name' => '6-ci MİKRORAYON','slug' => '6-ci-mikrorayon'),
            array('parent_id' => '3','name' => '7-ci MİKRORAYON','slug' => '7-ci-mikrorayon'),
            array('parent_id' => '3','name' => '8-ci MİKRORAYON','slug' => '8-ci-mikrorayon'),
            array('parent_id' => '3','name' => '9-ci MİKRORAYON','slug' => '9-ci-mikrorayon'),
            array('parent_id' => '3','name' => '10-ci MİKRORAYON','slug' => '10-ci-mikrorayon'),
            array('parent_id' => '3','name' => '11-ci MİKRORAYON','slug' => '11-ci-mikrorayon'),
            array('parent_id' => '3','name' => '12-ci MİKRORAYON','slug' => '12-ci-mikrorayon'),
            array('parent_id' => '3','name' => '13-ci MİKRORAYON','slug' => '13-ci-mikrorayon'),
            array('parent_id' => '3','name' => '14-ci MİKRORAYON','slug' => '14-ci-mikrorayon'),
            array('parent_id' => '3','name' => '15-ci MİKRORAYON','slug' => '15-ci-mikrorayon'),
            array('parent_id' => '3','name' => '16-ci MİKRORAYON','slug' => '16-ci-mikrorayon'),
            array('parent_id' => '3','name' => '17-ci MİKRORAYON','slug' => '17-ci-mikrorayon'),
            array('parent_id' => '3','name' => '18-ci MİKRORAYON','slug' => '18-ci-mikrorayon'),
            array('parent_id' => '3','name' => '19-ci MİKRORAYON','slug' => '19-ci-mikrorayon'),
            array('parent_id' => '3','name' => '20-ci MİKRORAYON','slug' => '20-ci-mikrorayon'),
            array('parent_id' => '3','name' => '21-ci MİKRORAYON','slug' => '21-ci-mikrorayon'),
            array('parent_id' => '3','name' => '1-ci MƏHƏLLƏ','slug' => '1-ci-mehelle'),
            array('parent_id' => '3','name' => '2-ci MƏHƏLLƏ','slug' => '2-ci-mehelle'),
            array('parent_id' => '3','name' => '3-ci MƏHƏLLƏ','slug' => '3-ci-mehelle'),
            array('parent_id' => '3','name' => '4-ci MƏHƏLLƏ','slug' => '4-ci-mehelle'),
            array('parent_id' => '3','name' => '5-ci MƏHƏLLƏ','slug' => '5-ci-mehelle'),
            array('parent_id' => '3','name' => '6-ci MƏHƏLLƏ','slug' => '6-ci-mehelle'),
            array('parent_id' => '3','name' => '7-ci MƏHƏLLƏ','slug' => '7-ci-mehelle'),
            array('parent_id' => '3','name' => '8-ci MƏHƏLLƏ','slug' => '8-ci-mehelle'),
            array('parent_id' => '3','name' => '9-ci MƏHƏLLƏ','slug' => '9-ci-mehelle'),
            array('parent_id' => '3','name' => '12-ci MƏHƏLLƏ','slug' => '12-ci-mehelle'),
            array('parent_id' => '3','name' => '13-ci MƏHƏLLƏ','slug' => '13-ci-mehelle'),
            array('parent_id' => '3','name' => '14-ci MƏHƏLLƏ','slug' => '14-ci-mehelle'),
            array('parent_id' => '3','name' => '15-ci MƏHƏLLƏ','slug' => '15-ci-mehelle'),
            array('parent_id' => '3','name' => '16-ci MƏHƏLLƏ','slug' => '16-ci-mehelle'),
            array('parent_id' => '3','name' => '17-ci MƏHƏLLƏ','slug' => '17-ci-mehelle'),
            array('parent_id' => '3','name' => '18-ci MƏHƏLLƏ','slug' => '18-ci-mehelle'),
            array('parent_id' => '3','name' => '19-ci MƏHƏLLƏ','slug' => '19-ci-mehelle'),
            array('parent_id' => '3','name' => '20-ci MƏHƏLLƏ','slug' => '20-ci-mehelle'),
            array('parent_id' => '3','name' => '21-ci MƏHƏLLƏ','slug' => '21-ci-mehelle'),
            array('parent_id' => '3','name' => '22-ci MƏHƏLLƏ','slug' => '22-ci-mehelle'),
            array('parent_id' => '3','name' => '23-ci MƏHƏLLƏ','slug' => '23-ci-mehelle'),
            array('parent_id' => '3','name' => '24-ci MƏHƏLLƏ','slug' => '24-ci-mehelle'),
            array('parent_id' => '3','name' => '25-ci MƏHƏLLƏ','slug' => '25-ci-mehelle'),
            array('parent_id' => '3','name' => '26-ci MƏHƏLLƏ','slug' => '26-ci-mehelle'),
            array('parent_id' => '3','name' => '30-ci MƏHƏLLƏ','slug' => '30-ci-mehelle'),
            array('parent_id' => '3','name' => '34-ci MƏHƏLLƏ','slug' => '34-ci-mehelle'),
            array('parent_id' => '3','name' => '36-ci MƏHƏLLƏ','slug' => '36-ci-mehelle'),
            array('parent_id' => '3','name' => '40-ci MƏHƏLLƏ','slug' => '40-ci-mehelle'),
            array('parent_id' => '3','name' => '41-ci MƏHƏLLƏ','slug' => '41-ci-mehelle'),
            array('parent_id' => '3','name' => '42-ci MƏHƏLLƏ','slug' => '42-ci-mehelle'),
            array('parent_id' => '3','name' => '43-ci MƏHƏLLƏ','slug' => '43-ci-mehelle'),
            array('parent_id' => '3','name' => '44-ci MƏHƏLLƏ','slug' => '44-ci-mehelle'),
            array('parent_id' => '3','name' => '45-ci MƏHƏLLƏ','slug' => '45-ci-mehelle'),
            array('parent_id' => '3','name' => '46-ci MƏHƏLLƏ','slug' => '46-ci-mehelle'),
            array('parent_id' => '3','name' => '47-ci MƏHƏLLƏ','slug' => '47-ci-mehelle'),
            array('parent_id' => '3','name' => '48-ci MƏHƏLLƏ','slug' => '48-ci-mehelle'),
            array('parent_id' => '3','name' => '49-ci MƏHƏLLƏ','slug' => '49-ci-mehelle'),
            array('parent_id' => '3','name' => '51-ci MƏHƏLLƏ','slug' => '51-ci-mehelle'),
            array('parent_id' => '3','name' => '52-ci MƏHƏLLƏ','slug' => '52-ci-mehelle'),
            array('parent_id' => '3','name' => '76-ci MƏHƏLLƏ','slug' => '76-ci-mehelle'),
            array('parent_id' => '3','name' => 'BİRLƏŞMİŞ MƏHƏLLƏ','slug' => 'birlesmis-mehelle'),
            array('parent_id' => '3','name' => 'SUMQAYIT ŞƏHƏR','slug' => 'sumqayit-seher'),
            array('parent_id' => '3','name' => 'ST.SUMQAYIT','slug' => 'stsumqayit'),
            array('parent_id' => '3','name' => 'İNŞAATÇILAR QƏSƏBƏSİ','slug' => 'insaatcilar-qesebesi'),
            array('parent_id' => '3','name' => 'KOTEC QƏSƏBƏSİ','slug' => 'kotec-qesebesi'),
            array('parent_id' => '3','name' => 'QURD DƏRƏSİ','slug' => 'qurd-deresi'),
            array('parent_id' => '3','name' => 'YAŞIL DƏRƏ','slug' => 'yasil-dere'),
            array('parent_id' => '3','name' => 'BTZ BAĞLARI','slug' => 'btz-baglari'),
            array('parent_id' => '3','name' => 'XƏZƏR BAĞLARI','slug' => 'xezer-baglari'),
            array('parent_id' => '3','name' => 'CORAT BAĞLARI','slug' => 'corat-baglari'),
            array('parent_id' => '3','name' => 'YENİ CORAT','slug' => 'yeni-corat'),
            array('parent_id' => '3','name' => 'HACI ZEYNALABDİN','slug' => 'haci-zeynalabdin'),
            array('parent_id' => '31','name' => 'BABƏK','slug' => 'babek'),
            array('parent_id' => '31','name' => 'CULFA','slug' => 'culfa'),
            array('parent_id' => '31','name' => 'ORDUBAD','slug' => 'ordubad'),
            array('parent_id' => '31','name' => 'ŞAHBUZ','slug' => 'sahbuz'),
            array('parent_id' => '31','name' => 'SƏDƏRƏK','slug' => 'sederek')
        );

        DB::table('cities')->insert($cities);
        foreach ($regions as $region) {
            $region['visible'] = 1;
            $region['deliver_price'] = rand(1,50);
            DB::table('cities')->insert($region);
        }
    }
}
