<?php

namespace App\Models;

use App\Traits\GlobalScopes;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class City extends Model
{
    use HasFactory,GlobalScopes;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::saving(function (City $translation){
            if ($translation->getAttribute('slug') == null || $translation->getAttribute('slug') == "")
            {
                $slug = $translation->generateSlug();
                $translation->setAttribute('slug', $slug);
            }
        });
    }

    public function generateSlug($number = 0)
    {
        $slug = Str::slug($this->getAttribute('name'));
        if ($number > 0)
        {
            $slug .= "$number";
        }

        if (City::query()->where('slug', $slug)->exists())
        {
            $number++;
            return $this->generateSlug($number);
        }

        return $slug;
    }

    protected $fillable = [
        'name','slug','deliver_price','parent_id','visible'
    ];

    public function children()
    {
        return $this->hasMany(self::class, 'parent_id');
    }
}
